Create a _config.yml

title: "Matthew Allen"
theme: jekyll-theme-primer
plugins:
  - jekyll-remote-theme

# Optional navigation
nav:
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/